sudo: reuried
services:
  - docker

before_install:
  - docker build -t subbs28/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run subbs28/react-test npm test -- --coverage

after_success:
  - docker build -t subbs28/multi-client ./client
  - docker build -t subbs28/multi-nginx ./nginx
  - docker build -t subbs28/multi-server ./server
  - docker build -t subbs28/multi-worker ./worker
  # Log in to the docker CLI
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  #take those images and push them to docker hub
  - docker push subbs28/multi-client
  - docker push subbs28/multi-nginx
  - docker push subbs28/multi-server
  - docker push subbs28/multi-worker


